"""update actor model

Revision ID: 410d75a31874
Revises: 74e661c04496
Create Date: 2026-03-10 17:50:30.202345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '410d75a31874'
down_revision: Union[str, Sequence[str], None] = '74e661c04496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('name_ru', sa.String(), nullable=False))
    op.add_column('actors', sa.Column('name_en', sa.String(), nullable=True))
    op.add_column('actors', sa.Column('birthplace', sa.String(), nullable=True))
    op.add_column('actors', sa.Column('deathplace', sa.String(), nullable=True))
    op.add_column('actors', sa.Column('growth', sa.Integer(), nullable=True))
    op.add_column('actors', sa.Column('poster_url', sa.String(), nullable=True))
    op.add_column('actors', sa.Column('profession', sa.String(), nullable=True))
    op.add_column('actors', sa.Column('facts', sa.JSON(), nullable=True))
    op.add_column('actors', sa.Column('films', sa.JSON(), nullable=True))
    op.drop_column('actors', 'last_name')
    op.drop_column('actors', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('actors', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('actors', 'films')
    op.drop_column('actors', 'facts')
    op.drop_column('actors', 'profession')
    op.drop_column('actors', 'poster_url')
    op.drop_column('actors', 'growth')
    op.drop_column('actors', 'deathplace')
    op.drop_column('actors', 'birthplace')
    op.drop_column('actors', 'name_en')
    op.drop_column('actors', 'name_ru')
