"""empty message

Revision ID: 42f6e473e446
Revises: a3b087b32f33
Create Date: 2026-01-19 15:55:33.208688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42f6e473e446'
down_revision: Union[str, Sequence[str], None] = 'a3b087b32f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('actors', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('actors', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('actors', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('actors', 'biography',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('actors', 'popularity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('actors', 'average_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('directors', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('directors', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('directors', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('directors', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('directors', 'biography',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('directors', 'average_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('genres', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('genres', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movie_actors', 'character_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movie_actors', 'is_lead_role',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('movie_actors', 'is_first_plan',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('movie_actors', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movies', 'original_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movies', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('movies', 'trailer_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('movies', 'release_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('movies', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movies', 'budget',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movies', 'revenue',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movies', 'kp_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('movies', 'imdb_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('movies', 'metacritic_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('movies', 'vote_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movies', 'popularity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('movies', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movies', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movies', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movies', 'content_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('reviews', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('reviews', 'likes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('similar_movies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_preferences', 'rating_tendency',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('user_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('watch_history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('watch_history', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('watch_history', 'watched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('watch_history', 'watch_duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('watch_history', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watch_history', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('watch_history', 'watch_duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('watch_history', 'watched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('watch_history', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('watch_history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_preferences', 'rating_tendency',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('similar_movies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reviews', 'likes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reviews', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('reviews', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('reviews', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movies', 'content_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('movies', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('movies', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('movies', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('movies', 'popularity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('movies', 'vote_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movies', 'metacritic_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('movies', 'imdb_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('movies', 'kp_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('movies', 'revenue',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movies', 'budget',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movies', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movies', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('movies', 'trailer_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('movies', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('movies', 'original_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('movie_actors', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movie_actors', 'is_first_plan',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('movie_actors', 'is_lead_role',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('movie_actors', 'character_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('genres', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('genres', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('directors', 'average_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('directors', 'biography',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('directors', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('directors', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('directors', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('directors', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actors', 'average_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('actors', 'popularity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('actors', 'biography',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('actors', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actors', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('actors', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actors', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
