"""empty message

Revision ID: 86dfe6e5bf76
Revises: f3b7d92f2088
Create Date: 2026-01-19 23:51:44.271321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86dfe6e5bf76'
down_revision: Union[str, Sequence[str], None] = 'f3b7d92f2088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('poster_url', sa.String(), nullable=True))
    op.drop_column('movies', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('movies', 'poster_url')
    # ### end Alembic commands ###
